apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - service-account.yaml
  - network-policy.yaml
  - disruption-budget.yaml
  - config-map.yaml
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: service
      app.kubernetes.io/part-of: k8kit-consumer
      app.kubernetes.io/managed-by: kustomize
images:
  - name: app-image
    newName: traefik/whoami
    digest: sha256:c4717a8d1f0134a7444e24f881160e033991f23027c6c5a9a3f8fd22e70d1d44
